### ISSUE TITLE
Can't preload module under mod_perl when EV is installed

### ISSUE THREAD

**Issue by freeside** [briandfoy/net-mac-vendor#10]
Since the Big Networking Switch in 1.25, I am unable to preload this module under mod_perl when EV is installed.  Apache fails to start -- worse, without any error message indicating the problem lies with EV, Net::MAC::Vendor, or Perl/mod_perl at all.

ref https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=805847

(I would respectfully suggest that perhaps a more traditional HTTP client library may be more appropriate at this time for the stable version of this CPAN module?)

Thanks.

**Comment by briandfoy** [comment]
From what I read it that Debian Bug thread, the problem was EV, not this module.

If you have patches, please submit pull requests. Thanks!
