### ISSUE TITLE
Strange issue with IEEE search

### ISSUE THREAD

**Issue by Frank071** [briandfoy/net-mac-vendor#13]
I recently came across some strange IEEE behaviour. When searching for OUI 00-23-3D (Novero) the IEEE searchpage returned over 10 results (!) none having anyhting to do with what I searched for (see https://github.com/briandfoy/net-mac-vendor/files/126283/Search.Results_.IEEE.Standards.MA-L.Public.Database.html.txt). As a result Net::MAC::Vendor returns no results (as it interprets the data returned not to find the OUI).

Not sure how to fix this...

**Comment by briandfoy** [comment]
Noted, but I'd need more info. A sample program would be nice.

**Comment by Frank071** [comment]
Agree. When and if I see it again I'll investigate.

**Comment by briandfoy** [comment]
This module is now maintained at https://github.com/karenetheridge/Net-MAC-Vendor
