### ISSUE TITLE
Co-maintenance

### ISSUE THREAD

**Issue by ivanfreeside** [briandfoy/net-mac-vendor#17]
Hi Brian,

Net::MAC::Vendor has not been updated in a year.  The outstanding issues are deal-breakers for us, and so our software has been unable to work with stock N:M:Vendor from CPAN for that time (we distributed a patched version instead).

Of course, we are all volunteers here.  I cannot expect or ask that you do any work and I thank you for writing N:M:Vendor in the first place!

What I would ask is for you to please consider adding some trusted co-maintainers.  My CPAN ID is IVAN.  I have both co-maintained and taken over modules in the past, and am happy to provide maintenance at your direction.  I could make some of the small fixes that have accumulated in the past year, and stay away from anything else or larger, allowing you to do that as time permits.

Thanks for your consideration,
Ivan Kohler
President and Head Geek, Freeside Internet Services, Inc.  http://freeside.biz/
Debian GNU/Linux developer | CPAN author | cat person | ski addict

**Comment by briandfoy** [comment]
Send some pull requests! Also, which issues are you having problems with? Are they in RT or in this issue queue?
