### ISSUE TITLE
Undefined subroutine "get"

### ISSUE THREAD

**Issue by openstrike** [briandfoy/net-mac-vendor#19]
I've been assigned Net::MAC::Vendor for this month's [CPAN PR Challenge](http://cpan-prc.org/) and was looking to improve some of the test coverage. In testing fetch_oui_from_custom() it transpires that the get() call in the line

```
my $html = get( $url );
```

doesn't exist. Looking elsewhere in the code we find instances of

```
__PACKAGE__->ua->get( $url );
```

so that seems the obvious fix. If you are happy for me to use this as a replacement I'll include it in the PR with the accompanying tests.

**Comment by briandfoy** [comment]
Fixed, thanks. Apparently this has no tests though, so I could use some of that.
