### ISSUE TITLE
Perldoc for load_cache seems incorrect

### ISSUE THREAD

**Issue by NetworkEng** [briandfoy/net-mac-vendor#23]
The perldoc for load_cache mentions the following:
> To load from a local file, use the "file://" scheme

I've tried multiple forms of this url format, but none would work, giving the error:
`Net::Mac::Vendor cache source [file://path/to/file] does not exist...`

Iterations include `file://path/to/file`, `file:///path/to/file`, `file://localhost/path/to/file` and even `file:/path/to/file`

The system in question is Linux (Ubuntu 16.04 to be specific).

Upon inspecting the source, it seems that it does a simple `-e` to check if the file exists.  When I nix the `file://` and simply use `/path/to/file` it does not throw an error, so I am assuming this is actually the correct format, despite the sentence mentioned in the perldoc.

Am I missing something?

**Comment by briandfoy** [comment]
I think this is related to the switch to Mojo::UserAgent and the schemes that can handle. I don't like that a feature may have disappeared, but it doesn't look like the code supports it. I adjusted the docs in 42528870d4eaac1ef87d52d59643c076a5fce825.

Thanks,
