### ISSUE TITLE
Module returns nothing

### ISSUE THREAD

**Issue by Vict0rC** [briandfoy/net-mac-vendor#8]
Hello,
I am trying to figure out, why is Net:MAC:Vendor module not working with my NetDB installation. I spent many hours testing, but without result... I hope, you can help me...
I tried to find help at perlmonks forum, but nobody was able to help.
So here is the problem.
I am using latest NetDB installation, everythin works fine in there, except translation of MAC addresses.
I am running Ubuntu 14.04 with perl 5.18.2, cpan 2.10, NMV 1.25, all dependencies installed - no errors anywhere.
So I created simple pl script to test NMV functionality:
```
#!/usr/bin/perl
use strict;
use Net::MAC::Vendor;
Net::MAC::Vendor::load_cache("/opt/netdb/netmacvendor/oui.txt");
my $winmac = "00:0d:93:29:f6:c2";
my $vendor_ref = Net::MAC::Vendor::fetch_oui_from_cache( $winmac );
print "Vendor of MAC $winmac is $vendor_ref \n"
```
$vendor_ref outputs nothing... I hade to change syntax "file://" to only "path" because it was returning error - file not exists. Perlmonk users adviced this to me http://perlmonks.org/index.pl?node_id=1144560
But still no luck..

I tried to install perlbrew with different perl versions, cpan versions, even NMV older versions, but still no output...

It only works when I run it like shell command "perl /usr/local/share/perl/5.18.2/Net/MAC/Vendor.pm 00:0d:93:29:f6:c2" and this returns "Apple, Inc."

I am really unhappy about it... I hope, you can help me to find the way out of this problem :(
Thank you very much.
Victor
P.S. Here is NMV intall log from CPAN
```
cpan[7]> force install Net::MAC::Vendor
Running install for module 'Net::MAC::Vendor'
Fetching with LWP:
http://cpan.lnx.sk/authors/id/B/BD/BDFOY/Net-MAC-Vendor-1.25.tar.gz
Fetching with LWP:
http://cpan.lnx.sk/authors/id/B/BD/BDFOY/CHECKSUMS
Checksum for /root/.cpan/sources/authors/id/B/BD/BDFOY/Net-MAC-Vendor-1.25.tar.gz ok
Scanning cache /root/.cpan/build for sizes
DONE
Configuring B/BD/BDFOY/Net-MAC-Vendor-1.25.tar.gz with Makefile.PL
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Net::MAC::Vendor
Writing MYMETA.yml and MYMETA.json
  BDFOY/Net-MAC-Vendor-1.25.tar.gz
  /usr/bin/perl Makefile.PL INSTALLDIRS=site -- OK
Running make for B/BD/BDFOY/Net-MAC-Vendor-1.25.tar.gz
cp lib/Net/MAC/Vendor.pm blib/lib/Net/MAC/Vendor.pm
cp README.pod blib/lib/Net/MAC/README.pod
Manifying 2 pod documents
  BDFOY/Net-MAC-Vendor-1.25.tar.gz
  /usr/bin/make -- OK
Running make test
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/compile.t ................ ok
t/extract_oui_from_html.t .. ok
t/fetch_oui.t .............. 4/?     # File path is /root/.cpan/build/Net-MAC-Vendor-1.25-ZjGBb4/extras/oui-20150808.txt
    # ...Loading cache...
    # ...Cache loaded...
t/fetch_oui.t .............. ok
t/fetch_oui_from_ieee.t .... ok
t/load_cache.t ............. ok
t/normalize_mac.t .......... ok
t/oui.t .................... 1/?     # URLs are http://standards-oui.ieee.org/oui.txt
    # URL is http://standards-oui.ieee.org/oui.txt
t/oui.t .................... ok
t/parse_oui.t .............. ok
t/pod.t .................... ok
t/pod_coverage.t ........... skipped: Test::Pod::Coverage required for testing POD
t/rt79369.t ................ ok
t/run.t .................... ok
All tests successful.
Files=12, Tests=50, 177 wallclock secs ( 0.09 usr  0.03 sys +  5.04 cusr  0.47 csys =  5.63 CPU)
Result: PASS
  BDFOY/Net-MAC-Vendor-1.25.tar.gz
  /usr/bin/make test -- OK
Running make install
Manifying 2 pod documents
Appending installation info to /usr/lib/perl/5.18/perllocal.pod
  BDFOY/Net-MAC-Vendor-1.25.tar.gz
  /usr/bin/make install  -- OK
```

**Comment by Vict0rC** [comment]
any idea? ;-(

**Comment by krauzo** [comment]
I've got exactly the same problem. I'm considering rewriting the vendor logic in netdb to parse vendor info from oui.txt in a different way. 

P.S. maybe it's environment speicific problem, I'm using the same OS and same perl and library versions.

**Comment by krauzo** [comment]
As I said, I've decided to rewrite the part of figuring out the vendor to put it into the NetDB.

First I do this in cron, after the download of new oui.txt file:

`cat /opt/netdb/data/oui.txt | grep "base 16" | sed 's/[ \t]*(base 16)[ \t]*/^/g' > /opt/netdb/data/oui2.txt`


This gives me the vendor list in a more useful version.

Apart from that, I've added a simple function to NetDB.pm:

    sub getVendorMIKR {
        my $inputMAC = shift;
        my $file = "/opt/netdb/data/oui2.txt";
        my $vendorName = "";

        # remove dots, colons and dashes
        $inputMAC = $inputMAC =~ s/\.//gr;
        $inputMAC = $inputMAC =~ s/\-//gr;
        $inputMAC = $inputMAC =~ s/\://gr;

        # make MAC uppercase
        $inputMAC = uc($inputMAC);

        # limit mac to first 6 chars
        $inputMAC = substr($inputMAC, 0, 6);

        # search for a prefix in oui file
        open my $vendorList, $file or die "Could not open $file: $!";

        while( my $line = <$vendorList>)  {

                my $position=index($line, $inputMAC);
                if ($position != -1) {
                        # found a matching prefix!
                        $vendorName = substr($line,7);
                        last;
                }
        }

        close $vendorList;

        # return vendor name
        return $vendorName;

    }

Inside NetDB.pm I've also replaced every occurence of following lines:
`my $winmac = getIEEEMac( $mac );`
`my $vendor_ref = Net::MAC::Vendor::fetch_oui_from_cache( $winmac );`
`$vendor = $$vendor_ref[0];`

with:

`$vendor = getVendorMIKR( $mac );`

and voila, it works! Maybe it's not the most elegant solution that could be, but it serves its purpose.

Regards

**Comment by Vict0rC** [comment]
Hello krauzo!
you are totally awesome!!! it works like a charm now!!! thank you very much!!!
One more last question, do you have any idea, how to translate older db mac vendors records too? Because your patch is just for future records :)
Thank you.
VicC

**Comment by krauzo** [comment]
Hi Vic,

Do you mean existing MAC records in the NetDB database? I think it should work with previous records as well, assuming you've replaced every occurrence of previous vendor logic with my function. 

As far as I see there are four places total in NetDB.pm to replace: 2 of them are for new records and 2 of them are for updating existing records.

**The first code section with insert/update logic:**

        #############
        # mac table #
        #############
        if ( $$row{"mac"} ) {
            print "Record Exists in mac: $$row{mac}\n" if $DEBUG>1;
            # Update vendor code
            $vendor = $$row{"vendor"};
            if ( !$vendor ) {

                $vendor = getVendorMIKR( $mac );

                #my $winmac = getIEEEMac( $mac );
                #my $vendor_ref = Net::MAC::Vendor::fetch_oui_from_cache( $winmac );
                #$vendor = $$vendor_ref[0];
            }
            $success = 1;
            $success = $updateMACSwitchport_h->execute( $switch, $port, $vendor, $mac_nd, $lastseen, $mac );
            die ("Update Failure in mac for $mac: $DBI::errstr\n") if !$success;
        }
        # Insert new entry in mac table
        else {
            # Vendor code lookup

            $vendor = getVendorMIKR( $mac );

            #my $winmac = getIEEEMac( $mac );
            #my $vendor_ref = Net::MAC::Vendor::fetch_oui_from_cache( $winmac );
            #$vendor = $$vendor_ref[0];
            $success = 1;
            $insertMACSwitchport_h->execute( $mac, $switch, $port, $vendor, $mac_nd, $lastseen, $lastseen );
            die ("Insert Failure in mac: $DBI::errstr\n") if !$success;

            print "|DEBUG|: Inserted: $mac, $switch, $port, $vendor, $mac_nd, $lastseen, $lastseen IN     mac table\n" if $DEBUG;
        }


**The second section with another pair of insert/update logic:**
        
        # Check MAC Table
        $selectMAC_h->execute( $mac );
        $row = $selectMAC_h->fetchrow_hashref();

        if ( $$row{"mac"} ) {
            print "Record Exists in mac: $$row{mac}\n" if $DEBUG>1;
            # Update vendor code
            $vendor = $$row{"vendor"};
            if ( !$vendor ) {
                
                $vendor = getVendorMIKR ( $mac );
                
                #my $winmac = getIEEEMac( $mac );
                #my $vendor_ref = Net::MAC::Vendor::fetch_oui_from_cache( $winmac );
                #$vendor = $$vendor_ref[0];
            }
            $success = 1;
            $success = $updateMAC_h->execute( $ip, $vendor, $lastseen, $lastseen, $mac );
            die ("Update Failure in mac for $mac: $DBI::errstr\n") if !$success;
        }
        # Insert new entry in to mac table
        else {
            #Get Vendor Code
            
            $vendor = getVendorMIKR ( $mac );
            
            #my $winmac = getIEEEMac( $mac );
            #my $vendor_ref = Net::MAC::Vendor::fetch_oui_from_cache( $winmac );
            #$vendor = $$vendor_ref[0];
            $success = 1;
            $insertMAC_h->execute( $mac, $ip, $vendor, $lastseen, $lastseen, $lastseen );
            die ("Insert Failure in mac for $mac: $DBI::errstr\n") if !$success;
            print "|DEBUG|: Inserted: ip:$ip, mac:$mac, vendor:$vendor IN mac table\n" if $DEBUG;
        }


Tell me if it works for you.

Regards

**Comment by Vict0rC** [comment]
Hello,
I've replaced every ocurance with your patch, but it only translates new or live devices, but it doesnt translate records with "last seen" parameter dated before I applied your patch...
VicC

**Comment by krauzo** [comment]
Ah, I see. Well that's true - I didn't think about the fact that NetDB takes actions only against devices that are alive at the script execution. In my case it's not relevant cause my database is fairly new. However in your case you should probably make it manually - write a simple script in Perl to "select" all the MACs from the MAC table and then do an MySQL "update" for every row.

Unfortunately I don't have time to write it now, and as I said it's not important in my case but you know where to start off :)

Regards

**Comment by Vict0rC** [comment]
Thank you, I'll try it ;-) Have a nice day.
Regards
VicC

**Comment by mysterfr** [comment]
Hi all,

FYI, I've simply solved this by changing the way the $ouidb variable gets populated.
In NetDB.pm, line 3461, remove the "file:/" concatenation to have :

`$ouidb           = $config->ouifile();`

And it just works : no massive line updates, no new function :)
